analyzer:
  strong-mode:
    # enables dart 2 type system (see https://www.dartlang.org/guides/language/analysis-options#performing-additional-type-checks)
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_element: info
    unused_import: error
    unused_local_variable: error
    dead_code: error
    override_on_non_overriding_method: error