name: dartbook
version: 0.1.1
description: The infamous Flex book component in pure Dart.
environment:
  sdk: '>=2.0.0-dev.54.0 <2.0.0'
dependencies:
  stagexl:
    git: https://github.com/bp74/StageXL/
  rockdot_commons:
    git: https://github.com/block-forest/rockdot-commons
dev_dependencies:
  #-------- Dart 2.0.0-dev.54 --------
  build_runner: ^0.8.8
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0