name: dartbook
version: 0.1.0
description: Port of Ruben Swieringa's Flexbook in pure Dart.
environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'
dependencies:
  logging: any
  stagexl: any
  rockdot_commons:
    git: https://github.com/block-forest/rockdot-commons
dev_dependencies:
  #-------- Dart 2.0.0-dev.54 --------
  build_runner: ^0.8.8
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0